### ISSUE TITLE
[ FEATURE ] 매칭

### ISSUE THREAD

**Issue by devbong92** [artbiit/4Dollar-Deffense-Server#2]
MATCH_REQUEST: 5,
MATCH_START_NOTIFICATION: 6,

**Comment by artbiit** [comment]
매치메이킹 디자인

[절차]
1. 매칭신청
2. 매칭 등록 핸들러에서 해당 유저의 최고 점수와 userId를 등록합니다.
3. 매치메이커 (독립된 워커)가 매칭 큐를 감시하며 순차적으로 매칭합니다.
4. 매칭된 두 유저에게 기본 정보를 전송합니다.

**Comment by artbiit** [comment]
레디스

1. 매칭의 경우 두개 이상의 데이터셋을 동시에 생성하거나 삭제해야 하는 경우가 발생합니다.
2. 따라서 레디스를 점유 후 전체 작업을 해 경쟁 상태를 회피합니다.
3. src/db/redis.js에 점유 함수를 추가해놨습니다.
