### ISSUE TITLE
[ FEATURE ] 몬스터 사망 통지

### ISSUE THREAD

**Issue by devbong92** [artbiit/4Dollar-Deffense-Server#9]
MONSTER_DEATH_NOTIFICATION: 20,
ENEMY_MONSTER_DEATH_NOTIFICATION: 21,

**Comment by WaDDaDDa** [comment]
클라이언트에서 monster가 base에 도달할시 base에 대미지를 주고 몬스터를 remove하고있습니다.
하지만 이 몬스터를 remove하는것을 서버에는 보내고 있지 않고 있어서 참고 바랍니다.
